services:
  app:
    image: 'ratings-service:latest'
    build:
      dockerfile: Dockerfile
    container_name: ratings-service
    depends_on:
      - ratings_db
    ports:
      - "8083:8080"
    networks:
      - microservices-network
    environment:
      - MONGO_DB=${MONGO_DB}

  ratings_db:
    image: 'mongo:latest'
    container_name: ratingsdb-service
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    networks:
      - microservices-network
    volumes:
      - /var/lib/docker/volumes/mongodb-data:/data/db

networks:
  microservices-network:
    external: true