services:
  app:
    image: 'ratings-service:latest'
    build:
      dockerfile: Dockerfile
    container_name: ratings-service
    depends_on:
      - ratings_db
    ports:
      - "8083:8080"
    networks:
      - microservices-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  ratings_db:
    image: postgres:latest
    container_name: ratings_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    networks:
      - microservices-network
    volumes:
      - /var/lib/docker/volumes/ratings-db:/var/lib/postgresql/data

networks:
  microservices-network:
    external: true